config/routes.rb
Rails.application.routes.draw do
  resources :posts

  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Frontview || Template</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.css">
    <link rel="stylesheet" href="assets/css/style.css">
    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>
  <body style="background-color: #fafafa;">
    <%= render 'shared/header' %>
    <%= render 'shared/alerts' %>
      <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_pack_tag 'main', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<section class="gallery portfolio-area section-gap">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="menu-content pb-70 col-lg-8">
        <div class="title text-center">
          <h3 class="mb-10">FrontView Template</h3>
          <p>This is frontview web template.</p>
        </div>
      </div>
    </div>
    <div class="filters">
      <form class="example" action="#" style="margin:auto;max-width:300px">
        <input type="text" placeholder="Search.." name="search">
        <button type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
    <div class="filters-content">
      <div class="row grid gallery-items">
        <div class="single-portfolio col-sm-4 all item">
          <div class="relative">
            <div class="thumb">
              <div class="overlay overlay-bg"></div>
              <img class="image img-fluid" src="https://viewfront.herokuapp.com/assets/p1.jpg" alt="Image1">
            </div>
            <a href="https://viewfront.herokuapp.com/assets/p1.jpg" class="img-pop-up">  
              <div class="middle">
                <div class="text align-self-center d-flex"><img src="https://viewfront.herokuapp.com/assets/preview.png" alt="Preview Image"></div>
              </div>
            </a>                                  
          </div>
        </div>
        <div class="single-portfolio col-sm-4 all item">
          <div class="relative">
            <div class="thumb">
              <div class="overlay overlay-bg"></div>
              <img class="image img-fluid" src="https://viewfront.herokuapp.com/assets/p2.jpg" alt="Image2">
            </div>
            <a href="https://viewfront.herokuapp.com/assets/p2.jpg" class="img-pop-up">  
              <div class="middle">
                <div class="text align-self-center d-flex"><img src="https://viewfront.herokuapp.com/assets/preview.png" alt="Preview Image"></div>
              </div>
            </a>                                  
          </div>
        </div>
        <div class="single-portfolio col-sm-4 all item">
          <div class="relative">
            <div class="thumb">
              <div class="overlay overlay-bg"></div>
              <img class="image img-fluid" src="https://viewfront.herokuapp.com/assets/p3.jpg" alt="Image3">
            </div>
            <a href="https://viewfront.herokuapp.com/assets/p3.jpg" class="img-pop-up">  
              <div class="middle">
                <div class="text align-self-center d-flex"><img src="https://viewfront.herokuapp.com/assets/preview.png" alt="Preview Image"></div>
              </div>
            </a>                                  
          </div>
        </div>
        <div class="single-portfolio col-sm-4 all item">
          <div class="relative">
            <div class="thumb">
              <div class="overlay overlay-bg"></div>
              <img class="image img-fluid" src="https://viewfront.herokuapp.com/assets/p4.jpg" alt="Image4">
            </div>
            <a href="https://viewfront.herokuapp.com/assets/p4.jpg" class="img-pop-up">  
              <div class="middle">
                <div class="text align-self-center d-flex"><img src="https://viewfront.herokuapp.com/assets/preview.png" alt="Preview Image"></div>
              </div>
            </a>                                  
          </div>
        </div>
        <div class="single-portfolio col-sm-4 all item">
          <div class="relative">
            <div class="thumb">
              <div class="overlay overlay-bg"></div>
              <img class="image img-fluid" src="https://viewfront.herokuapp.com/assets/p5.jpg" alt="Image5">
            </div>
            <a href="https://viewfront.herokuapp.com/assets/p5.jpg" class="img-pop-up">  
              <div class="middle">
                <div class="text align-self-center d-flex"><img src="https://viewfront.herokuapp.com/assets/preview.png" alt="Preview Image"></div>
              </div>
            </a>                                  
          </div>
        </div>
        <div class="single-portfolio col-sm-4 all item">
          <div class="relative">
            <div class="thumb">
              <div class="overlay overlay-bg"></div>
              <img class="image img-fluid" src="https://viewfront.herokuapp.com/assets/p6.jpg" alt="Image6">
            </div>
            <a href="https://viewfront.herokuapp.com/assets/p6.jpg" class="img-pop-up">  
              <div class="middle">
                <div class="text align-self-center d-flex"><img src="https://viewfront.herokuapp.com/assets/preview.png" alt="Preview Image"></div>
              </div>
            </a>                                  
          </div>
        </div>
      </div>
      <div class="pagination">
        <div class="prev">Prev</div>
        <div class="page">Page <span class="page-num"></span></div>
        <div class="next">Next</div>
      </div>
    </div>
  </div>
</section>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/shared/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_footer.html.erb
<footer class="footer-area section-gap">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="menu-content pb-70 col-lg-8">
        <div class="title text-center">
          <h3 class="mb-10"><i>FrontView</i></h3>
          <p style="color: #1a2359;"><i>Copyright &copy;<script>document.write(new Date().getFullYear());</script> FrontView || All rights reserved</i></p>
        </div>
      </div>
    </div>
  </div>
</footer>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="https://www.solodev.com/assets/pagination/jquery.twbsPagination.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>

app/views/shared/_header.html.erb
<header id="header">
  <div class="container main-menu">
    <div class="row align-items-center justify-content-between d-flex">
      <div id="logo">
        <a href="/"><img src="assets/logo.png" alt="" title="" /></a>
      </div>
      <nav id="nav-menu-container">
        <ul class="nav-menu">
          <li><a href="/">Home</a></li>
          <li><a href="#">Other Pics</a></li>
          <li><a href="#">Info</a></li>
        </ul>
      </nav>       
    </div>
  </div>
</header>